=== JonatanBadillo/Semantic-Web/Práctica 2/receta.dtd
<!ELEMENT Receta (Nombre, Ingredientes, Instrucciones, TiempoPreparacion, Porciones)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Ingredientes (Ingrediente+)>
<!ELEMENT Ingrediente (NombreIngrediente, Cantidad, Unidad)>
<!ELEMENT NombreIngrediente (#PCDATA)>
<!ELEMENT Cantidad (#PCDATA)>
<!ELEMENT Unidad (#PCDATA)>
<!ELEMENT Instrucciones (Paso+)>
<!ELEMENT Paso (#PCDATA)>
<!ELEMENT TiempoPreparacion (#PCDATA)>
<!ELEMENT Porciones (#PCDATA)>

=== JonatanBadillo/Semantic-Web/Práctica 2/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Receta SYSTEM "receta.dtd">
<Receta>
    <Nombre>Spaghetti a la Boloñesa</Nombre>
    <Ingredientes>
        <Ingrediente>
            <NombreIngrediente>Spaghetti</NombreIngrediente>
            <Cantidad>200</Cantidad>
            <Unidad>gramos</Unidad>
        </Ingrediente>
        <Ingrediente>
            <NombreIngrediente>Carne molida</NombreIngrediente>
            <Cantidad>500</Cantidad>
            <Unidad>gramos</Unidad>
        </Ingrediente>
    </Ingredientes>
    <Instrucciones>
        <Paso>Hervir el spaghetti en agua con sal durante 10 minutos.</Paso>
        <Paso>Cocinar la carne en una sartén con aceite.</Paso>
        <Paso>Mezclar la carne con la salsa de tomate.</Paso>
        <Paso>Servir el spaghetti con la salsa encima.</Paso>
    </Instrucciones>
    <TiempoPreparacion>30 minutos</TiempoPreparacion>
    <Porciones>4</Porciones>
</Receta>
